version: '3.8'

services:
  app:
    container_name: ofincar
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.15
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: ""
    environment:
      MYSQL_DATABASE: ofincar_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - ..:/home/app:cached
    command: sleep infinity
    network_mode: service:mysql

  mysql:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - .docker/mysql/data:/var/lib/mysql
      - .docker/mysql/config:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: ofincar_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    healthcheck:
      test: "exit 0"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: password
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
